export type ConversationFilterResponse = {
  meta: {
    mine_count: number;
    unassigned_count: number;
    assigned_count: number;
    all_count: number;
  };
  payload: Array<{
    id: number;
    messages: Array<{
      id: number;
      content: string;
      account_id: number;
      inbox_id: number;
      conversation_id: number;
      message_type: number;
      created_at: number;
      updated_at: number;
      private: boolean;
      status: string;
      source_id: string;
      content_type: string;
      content_attributes?: Record<string, unknown>;
      sender_type: string;
      sender_id: number;
      external_source_ids?: Record<string, unknown>;
      additional_attributes?: Record<string, unknown>;
      processed_message_content: string;
      sentiment?: Record<string, unknown>;
      conversation?: Record<string, unknown>;
      attachment?: Record<string, unknown>;
      sender?: Record<string, unknown>;
    }>;
    account_id: number;
    uuid: string;
    additional_attributes?: Record<string, unknown>;
    agent_last_seen_at: number;
    assignee_last_seen_at: number;
    can_reply: boolean;
    contact_last_seen_at: number;
    custom_attributes?: Record<string, unknown>;
    inbox_id: number;
    labels: Array<string>;
    muted: boolean;
    snoozed_until: number;
    status: string;
    created_at: number;
    updated_at: number;
    timestamp: string;
    first_reply_created_at: number;
    unread_count: number;
    last_non_activity_message: {
      id: number;
      content: string;
      account_id: number;
      inbox_id: number;
      conversation_id: number;
      message_type: number;
      created_at: number;
      updated_at: number;
      private: boolean;
      status: string;
      source_id: string;
      content_type: string;
      content_attributes?: Record<string, unknown>;
      sender_type: string;
      sender_id: number;
      external_source_ids?: Record<string, unknown>;
      additional_attributes?: Record<string, unknown>;
      processed_message_content: string;
      sentiment?: Record<string, unknown>;
      conversation?: Record<string, unknown>;
      attachment?: Record<string, unknown>;
      sender?: Record<string, unknown>;
    };
    last_activity_at: number;
    priority: string;
    waiting_since: number;
    sla_policy_id: number;
    applied_sla?: Record<string, unknown>;
    sla_events?: Array<Record<string, unknown>>;
    meta: {
      sender: {
        additional_attributes?: Record<string, unknown>;
        availability_status: string;
        email: string;
        id: number;
        name: string;
        phone_number: string;
        blocked: boolean;
        identifier: string;
        thumbnail: string;
        custom_attributes?: Record<string, unknown>;
        last_activity_at: number;
        created_at: number;
      };
      channel: string;
      assignee: {
        id: number;
        access_token: string;
        account_id: number;
        available_name: string;
        avatar_url: string;
        confirmed: boolean;
        display_name: string;
        message_signature: string;
        email: string;
        hmac_identifier: string;
        inviter_id: number;
        name: string;
        provider: string;
        pubsub_token: string;
        role: string;
        ui_settings?: Record<string, unknown>;
        uid: string;
        type: string;
        custom_attributes?: Record<string, unknown>;
        accounts: Array<{
          id: number;
          name: string;
          status: string;
          active_at: string;
          role: string;
          permissions: Array<string>;
          availability: string;
          availability_status: string;
          auto_offline: boolean;
          custom_role_id: number;
          custom_role?: Record<string, unknown>;
        }>;
      };
      hmac_verified: boolean;
    };
  }>;
};
